///////////////////////////////////////////////////////////////////////////////
// StatsCmd.cs : Implements the "callbackstats" command.                     //
// Application : CLR V4 Profiler Test Infrastructure                         //
// Author      : Mithun Shanbhag, mithuns@microsoft.com                      //
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using System.IO;

namespace OrangeClient
{
    //////////////////////////////////////////////////
    // ----< partial class OrangeCoreExtension >----//
    //////////////////////////////////////////////////

    public sealed partial class OrangeCoreExtension
    {

        /// <summary>
        /// The "STATS" command.
        /// 
        ///         
        /// </summary>
        /// <param name="arguments"></param>
        [
            CommandDescription(
                CommandName = "callbackstats",
                MinimumAbbrev = 1,
                ShortHelp = @"Parses the xml report generated by the 'mem' command and displays raw profiler callback count.",
                LongHelp = ""
            )
        ]
        public static void CallbackStats(string arguments)
        {
            if (null == arguments)
                throw new ArgumentNullException("arguments");
            if (0 == arguments.Length)
                throw new OrangeShellException("Did you pass in location of the xml report file?" + QuickCmdUsageOptions("CallbackStats"));

            arguments = Environment.ExpandEnvironmentVariables(arguments).ToLower().Trim().StripLeadingLaggingQuotes();

            if (!File.Exists(arguments))
                throw new OrangeShellException("Could not locate the file: " + arguments + ".\r\n" +
                                               "Are you sure you have specified the correct path and filename?");



            ProfilerStats stats = new ProfilerStats();

            var callbacks = from item in StreamXML(arguments)
                            select item;

            foreach (var callback in callbacks)
            {
                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_GarbageCollectionStarted))
                    ++stats.cGarbageCollectionStarted;

                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_GarbageCollectionFinished))
                    ++stats.cGarbageCollectionFinished;

                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_RuntimeSuspendStarted))
                    ++stats.cRuntimeSuspendStarted;

                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_RuntimeSuspendFinished))
                    ++stats.cRuntimeSuspendFinished;

                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_RuntimeSuspendAborted))
                    ++stats.cRuntimeSuspendAborted;
                    
                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_MovedReferences))
                    ++stats.cMovedReferences;

                if (callback.Name.ToString().Equals(CallbackStrings.CALLBACK_SurvivingReferences))
                    ++stats.cSurvivingReferences;    
            }


            //Debug.Assert((stats.cGarbageCollectionStarted == stats.cGarbageCollectionFinished));
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_GarbageCollectionStarted, stats.cGarbageCollectionStarted);
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_GarbageCollectionFinished, stats.cGarbageCollectionFinished);

            //Debug.Assert((stats.cRuntimeSuspendStarted == stats.cRuntimeSuspendFinished + stats.cRuntimeSuspendAborted));            
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_RuntimeSuspendStarted, stats.cRuntimeSuspendStarted);
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_RuntimeSuspendFinished, stats.cRuntimeSuspendFinished);
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_RuntimeSuspendAborted, stats.cRuntimeSuspendAborted);
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_MovedReferences, stats.cMovedReferences);
            Console.WriteLine("{0} = {1}", CallbackStrings.CALLBACK_SurvivingReferences, stats.cSurvivingReferences);

        }



        private static IEnumerable<XElement> StreamXML(string file)
        {
            using (XmlReader reader = XmlReader.Create(file))
            {
                reader.MoveToContent();

                while (reader.Read())
                {
                    if (reader.NodeType == XmlNodeType.Element)
                    {
                        XElement element = (XElement)XElement.ReadFrom(reader);
                        yield return element;
                    }
                }
                reader.Close();
            }
        }


        
    }
}